### ISSUE TITLE
Do we need pytorch package?

### ISSUE THREAD

**Issue by hanson-hschang** [hanson-hschang/ros2-vicon#12]
Since the [FastRodReconstruction](https://github.com/tixianw/FastRodReconstruction/commit/2867302c2352f50e5714ac143b435fcd1873f0f9) is now a package, I'll need to do the package installation anyway, I think it might be better to remove the `pytorch` in the image so that it won't conflict? Any thoughts, @skim0119 ?

**Comment by skim0119** [comment]
I think it works either way. I've seen docker images including pytorch/tensorflow natively, because they are big packages to install.

Within the image, we run some `cache-cleanup` to reduce the image size, but those steps will be neglected if we let users to install packages in each container. Downside is that we might need to provide cpu-image and gpu-image separately.

At this point, we can just specify in readme that python/pytorch are natively provided, and indicate their version. We let users to re-install if they need other version.

**Comment by hanson-hschang** [comment]
If we need to provide both the cpu-image and gpu-image, it might be better to remove the pytorch and let users to install there own package... It doesn't take too much time to install I believe. (At least for me today when I install the FastRodReconstruction repository)

Also, the python version is needed to be specified as well, I think.
